-- Enum types for BetBlocker
CREATE TYPE account_role AS ENUM ('user', 'partner', 'authority', 'admin');
CREATE TYPE platform_type AS ENUM ('windows', 'macos', 'linux', 'android', 'ios');
CREATE TYPE device_status AS ENUM ('pending', 'active', 'offline', 'unenrolling', 'unenrolled');
CREATE TYPE enrollment_tier AS ENUM ('self', 'partner', 'authority');
CREATE TYPE enrollment_status AS ENUM ('pending', 'active', 'unenroll_requested', 'unenroll_approved', 'unenrolling', 'unenrolled', 'expired');
CREATE TYPE unenrollment_policy_type AS ENUM ('time_delayed', 'partner_approval', 'authority_approval');
CREATE TYPE unenroll_request_status AS ENUM ('pending', 'approved', 'denied', 'expired', 'cancelled');
CREATE TYPE partner_relationship_status AS ENUM ('pending', 'active', 'revoked');
CREATE TYPE partner_role AS ENUM ('accountability_partner', 'therapist', 'authority_rep');
CREATE TYPE organization_type AS ENUM ('family', 'therapy_practice', 'court_program', 'employer', 'other');
CREATE TYPE org_member_role AS ENUM ('admin', 'member');
CREATE TYPE blocklist_source AS ENUM ('curated', 'automated', 'federated', 'community');
CREATE TYPE blocklist_entry_status AS ENUM ('pending_review', 'active', 'inactive', 'rejected');
CREATE TYPE gambling_category AS ENUM ('online_casino', 'sports_betting', 'poker', 'lottery', 'bingo', 'fantasy_sports', 'crypto_gambling', 'affiliate', 'payment_processor', 'other');
CREATE TYPE event_type AS ENUM ('block', 'bypass_attempt', 'tamper_detected', 'tamper_self_healed', 'vpn_detected', 'enrollment_created', 'enrollment_modified', 'unenroll_requested', 'unenroll_completed', 'heartbeat', 'agent_started', 'agent_updated', 'blocklist_updated');
CREATE TYPE event_category AS ENUM ('dns', 'app', 'browser', 'tamper', 'enrollment', 'heartbeat', 'system');
CREATE TYPE event_severity AS ENUM ('info', 'warning', 'critical');
CREATE TYPE reporting_level AS ENUM ('none', 'aggregated', 'detailed', 'full_audit');
CREATE TYPE vpn_detection_mode AS ENUM ('disabled', 'log', 'alert', 'lockdown');
CREATE TYPE tamper_response AS ENUM ('log', 'alert_user', 'alert_partner', 'alert_authority');
CREATE TYPE subscription_plan AS ENUM ('free', 'standard', 'partner_tier', 'institutional');
CREATE TYPE subscription_status AS ENUM ('trialing', 'active', 'past_due', 'cancelled', 'expired');
CREATE TYPE federated_report_status AS ENUM ('pending', 'promoted', 'rejected', 'duplicate');
